#!/bin/bash

TEXFILE=thesis

for arg in $@
do
	if test $arg = '--release'; then
		TEXFILE=release
	fi
done

[ -d build ] || mkdir ./build
rm ./thesis.pdf

echo "Compiling $TEXFILE.tex";
latexmk -xelatex -shell-escape -jobname=./build/thesis ./$TEXFILE.tex
cp build/thesis.pdf ./thesis.pdf

open thesis.pdf
